site_name: MID360 LOITER Docs
site_url: https://nonsaya.github.io/MID360/
repo_url: https://github.com/nonsaya/MID360
repo_name: nonsaya/MID360
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - include-markdown
nav:
  - Home: index.md
  - LOITER: LOITER.md
  - Backup & Restore: backup_restore.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

